### ISSUE TITLE
invalid handling of multiple letter occurances

### ISSUE THREAD

**Issue by jj15warrior** [olix3001/wordle-bot#1]
```
possible words: filii, lippy, pupil, [...few more...]
best guess: filii
suggested answer: filii
28/12972
selected word >> filii
pattern (filii)>> 00120
matching...
analyzing wordlist: 0words [00:00, ?words/s]
There are no more options
```

the word was pupil. what i think is happening (without reading this spaghetti) is that on the last spot fili _i_ it sees a 0 and therefore removes all words with i.

**Comment by olix3001** [comment]
Emm, I don't plan to fix it, I think I knew about it, but not sure for now.
This project is kinda archived as It has been just an experiment :>
